from .datamodelschema import DataModelSchema, DataModelSchemaData

def pack(dir_path: str, out_pbit_file_path: str): ...
def unpack(pbit_file_path: str, out_dir_path: str): ...
def write_model(pbit_file_path: str, source: DataModelSchemaData | DataModelSchema): ...
def read_model(pbit_file_path: str) -> DataModelSchemaData: ...
def load_model(pbit_file_path: str) -> DataModelSchema: ...
